/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8ff23136-f896-43b7-b691-94f300865eba",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_H0DFFLAO2",
    "aws_user_pools_web_client_id": "400cf0v0i2rvs86rprnjqvq0ir",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uxni7ozzpnh3ndwznzousryrma.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7pkg5iblljcprpm3bqnw3v6gvy",
    "aws_user_files_s3_bucket": "sssbucket175129-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
